using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
              
namespace GuessTheNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            // The code provided will print ‘Hello World’ to the console.
            // Press Ctrl+F5 (or go to Debug > Start Without Debugging) to run your app.
            Console.WriteLine("Guess The Number");
            Console.WriteLine("By Owen Penman");
            Console.WriteLine("");
            Console.WriteLine("Guess a random number that's generated by the PC between 1 and 10!");


            Random rand = new Random();
            int Guesses =  0;
            int secretNumber = rand.Next(1,10);
            
            //Console.WriteLine("Secret Number is " + secretNumber);

            
            int playerInput = Convert.ToInt32(Console.ReadLine());
            Guesses++;
            
           

            while (playerInput != secretNumber)
            {
                

                Console.WriteLine("You guessed " + playerInput);
                if (playerInput == secretNumber)
                {
                    Console.WriteLine("Congrats You guessed correct! The number was " + secretNumber);
                }
                else
                {
                    Console.WriteLine("Sorry! You didn't guess the right number. Try Again!");

                    if (secretNumber < playerInput)
                    {
                        Console.WriteLine("Aim Lower!");
                    }
                    else
                    {
                        Console.WriteLine("Aim Higher!");
                    }

                    playerInput = Convert.ToInt32(Console.ReadLine());
                    ++Guesses;
                }
            }


            Console.WriteLine("Congrats You guessed correct! The number was " + secretNumber);
            Console.WriteLine("You did this in " + Guesses + " tries!"); 



            Console.ReadKey();

            // Go to http://aka.ms/dotnet-get-started-console to continue learning how to build a console app! 
        }
    }
}

